#!/usr/bin/env python
from argparse import ArgumentParser, Namespace
from collections.abc import Iterator
from pathlib import Path


def is_id_valid(id: int) -> bool:
    return not str(id) in f"{id}{id}"[1:-1]


def invalid_ids(id_range: str) -> Iterator[int]:
    ids: list[str] = id_range.split("-")
    start: int = int(ids[0])
    end: int = int(ids[1])
    for id in range(start, end + 1):
        if is_id_valid(id):
            continue
        yield id


def main(input_path: Path) -> int:
    input: str = input_path.read_text()
    output: int = 0
    for id_range in input.split(","):
        for id in invalid_ids(id_range):
            output += int(id)
    return output


if __name__ == "__main__":
    parser: ArgumentParser = ArgumentParser()
    parser.add_argument("path", type=Path, nargs=1)
    args: Namespace = parser.parse_args()
    outcome: int = main(args.path[0])
    print(f"Outcome: {outcome}")
