#!/usr/bin/env python
from argparse import ArgumentParser, Namespace
from collections.abc import Callable
from pathlib import Path

type MoveFunctionType = Callable[[int, int], int]

POSITION_MIN: int = 0
POSITION_MAX: int = 99
POSITION_COUNT: int = POSITION_MAX - POSITION_MIN + 1
STARTING_POSITION: int = 50
MOVE_FUNCTIONS: dict[str, MoveFunctionType] = {
    "R": lambda pos, dist: pos + dist,
    "L": lambda pos, dist: pos - dist,
}


def new_position(current_position: int, instruction: str) -> int:
    direction: str = instruction[0]
    distance: int = int(instruction[1:])
    new_position: int = MOVE_FUNCTIONS[direction](current_position, distance)
    return new_position % POSITION_COUNT


def main(instructions_path: Path) -> int:
    instructions: str = instructions_path.read_text()
    current_position: int = STARTING_POSITION
    password: int = 0
    for instruction in instructions.splitlines():
        current_position = new_position(current_position, instruction)
        if current_position == 0:
            password += 1
    return password


if __name__ == "__main__":
    parser: ArgumentParser = ArgumentParser()
    parser.add_argument("path", type=Path, nargs=1)
    args: Namespace = parser.parse_args()
    password: int = main(args.path[0])
    print(f"The password is {password}")
