#!/usr/bin/env python
from argparse import ArgumentParser, Namespace
from collections.abc import Callable
from pathlib import Path

type MoveFunctionType = Callable[[int, int], int]

POSITION_MIN: int = 0
POSITION_MAX: int = 99
POSITION_COUNT: int = POSITION_MAX - POSITION_MIN + 1
STARTING_POSITION: int = 50
MOVE_FUNCTIONS: dict[str, MoveFunctionType] = {
    "R": lambda pos, dist: pos + dist,
    "L": lambda pos, dist: pos - dist,
}


class PasswordCalculator:
    def __init__(self) -> None:
        self.position_curr = STARTING_POSITION
        self.password: int = 0

    @property
    def position_curr(self) -> int:
        return self._position_curr

    @position_curr.setter
    def position_curr(self, value: int) -> None:
        if value == 0:
            self.password += 1
        self._position_curr: int = value

    def move(self, instruction: str) -> None:
        direction: str = instruction[0]
        distance: int = int(instruction[1:])
        move_function: MoveFunctionType = MOVE_FUNCTIONS[direction]
        for step in range(distance):
            position_new: int = move_function(self.position_curr, 1)
            self.position_curr = position_new % POSITION_COUNT

def main(instructions_path: Path) -> int:
    calculator: PasswordCalculator = PasswordCalculator()
    instructions: str = instructions_path.read_text()
    for instruction in instructions.splitlines():
        calculator.move(instruction)
    return calculator.password


if __name__ == "__main__":
    parser: ArgumentParser = ArgumentParser()
    parser.add_argument("path", type=Path, nargs=1)
    args: Namespace = parser.parse_args()
    password: int = main(args.path[0])
    print(f"The password is {password}")
